# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env:
      JAVA_HOME: /usr/lib/jvm/java-15-openjdk/

    steps:
    - uses: actions/checkout@v2
    - name: Release
      uses: qcastel/github-actions-maven-release@60470300dc4d8e61dfa52f16040e387b430c3541
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
