# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '15'
        architecture: x64
        targets: 'JAVA_HOME'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Release
      uses: qcastel/github-actions-maven-release@60470300dc4d8e61dfa52f16040e387b430c3541
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
